import { Category, SourceType } from "../src/generated/prisma/client"
import { getDb } from "../src/lib/db"

const sources = [
  {
    name: "arXiv AI",
    slug: "arxiv-ai",
    url: "https://arxiv.org/",
    type: SourceType.FACT,
    category: Category.AI,
    provider: "arxiv",
    enabled: true,
    fetchIntervalMinutes: 1_440,
    reliabilityScore: 95,
    notes: "Official arXiv metadata API; AI/ML categories only.",
    config: { categories: ["cs.AI", "cs.CL", "cs.LG", "cs.CV", "stat.ML"], limit: 50 },
  },
  {
    name: "GitHub AI Trending",
    slug: "github-ai-trending",
    url: "https://github.com/trending",
    type: SourceType.FACT,
    category: Category.DEVTOOLS,
    provider: "github",
    enabled: true,
    fetchIntervalMinutes: 360,
    reliabilityScore: 88,
    notes: "Uses the official GitHub Search API instead of scraping Trending HTML.",
    config: { query: "topic:artificial-intelligence stars:>100", limit: 30 },
  },
  {
    name: "Hugging Face Models",
    slug: "huggingface-models",
    url: "https://huggingface.co/models",
    type: SourceType.FACT,
    category: Category.AI,
    provider: "huggingface",
    enabled: true,
    fetchIntervalMinutes: 180,
    reliabilityScore: 90,
    notes: "Public Hugging Face Hub model metadata.",
    config: { limit: 30, sort: "trendingScore" },
  },
  {
    name: "CoinGecko Markets",
    slug: "coingecko-markets",
    url: "https://www.coingecko.com/",
    type: SourceType.FACT,
    category: Category.CRYPTO,
    provider: "coingecko",
    enabled: true,
    fetchIntervalMinutes: 30,
    reliabilityScore: 90,
    notes: "Latest market state only; no historical snapshot series in MVP.",
    config: { limit: 30, currency: "usd" },
  },
  {
    name: "DefiLlama Protocols",
    slug: "defillama-protocols",
    url: "https://defillama.com/protocols",
    type: SourceType.FACT,
    category: Category.CRYPTO,
    provider: "defillama",
    enabled: true,
    fetchIntervalMinutes: 60,
    reliabilityScore: 88,
    notes: "Public DefiLlama protocol TVL endpoint.",
    config: { limit: 30 },
  },
  {
    name: "OpenAI News",
    slug: "openai-news-rss",
    url: "https://openai.com/news/rss.xml",
    type: SourceType.NEWS,
    category: Category.AI,
    provider: "rss",
    enabled: true,
    fetchIntervalMinutes: 120,
    reliabilityScore: 90,
    notes: "Official OpenAI RSS feed.",
    config: { limit: 50 },
  },
  {
    name: "Google DeepMind Blog",
    slug: "google-deepmind-blog",
    url: "https://deepmind.google/blog/rss.xml",
    type: SourceType.NEWS,
    category: Category.AI,
    provider: "rss",
    enabled: true,
    fetchIntervalMinutes: 180,
    reliabilityScore: 90,
    notes: "Official Google DeepMind RSS feed.",
    config: { limit: 50 },
  },
  {
    name: "Hugging Face Blog",
    slug: "huggingface-blog",
    url: "https://huggingface.co/blog/feed.xml",
    type: SourceType.NEWS,
    category: Category.AI,
    provider: "rss",
    enabled: true,
    fetchIntervalMinutes: 180,
    reliabilityScore: 86,
    notes: "Official Hugging Face blog RSS feed.",
    config: { limit: 50 },
  },
  {
    name: "TechCrunch AI",
    slug: "techcrunch-ai",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    type: SourceType.NEWS,
    category: Category.AI,
    provider: "rss",
    enabled: true,
    fetchIntervalMinutes: 60,
    reliabilityScore: 72,
    notes: "TechCrunch Artificial Intelligence RSS feed.",
    config: { limit: 50 },
  },
  {
    name: "The Verge AI",
    slug: "theverge-ai",
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    type: SourceType.NEWS,
    category: Category.TECH,
    provider: "rss",
    enabled: true,
    fetchIntervalMinutes: 60,
    reliabilityScore: 72,
    notes: "The Verge AI RSS feed.",
    config: { limit: 50 },
  },
  {
    name: "Hacker News Top",
    slug: "hackernews-top",
    url: "https://news.ycombinator.com/news",
    type: SourceType.OPINION,
    category: Category.TECH,
    provider: "hackernews",
    enabled: true,
    fetchIntervalMinutes: 15,
    reliabilityScore: 58,
    notes: "Official Hacker News Firebase API; community signal, not a fact source.",
    config: { feed: "topstories", limit: 30 },
  },
  {
    name: "Hacker News Ask",
    slug: "hackernews-ask",
    url: "https://news.ycombinator.com/ask",
    type: SourceType.OPINION,
    category: Category.DEVTOOLS,
    provider: "hackernews",
    enabled: true,
    fetchIntervalMinutes: 30,
    reliabilityScore: 52,
    notes: "Official Hacker News Firebase API; Ask HN discussions.",
    config: { feed: "askstories", limit: 30 },
  },
  {
    name: "X AI Watchlist",
    slug: "x-ai-watchlist-placeholder",
    url: "https://x.com/",
    type: SourceType.OPINION,
    category: Category.AI,
    provider: "x-placeholder",
    enabled: false,
    fetchIntervalMinutes: 60,
    reliabilityScore: 40,
    notes: "Placeholder only. Requires the official X API and an explicit watchlist.",
    config: {},
  },
  {
    name: "Zhihu AI",
    slug: "zhihu-ai-placeholder",
    url: "https://www.zhihu.com/",
    type: SourceType.OPINION,
    category: Category.AI,
    provider: "zhihu-placeholder",
    enabled: false,
    fetchIntervalMinutes: 120,
    reliabilityScore: 42,
    notes: "Placeholder only. Do not scrape; verify official/RSSHub and terms first.",
    config: {},
  },
  {
    name: "Xueqiu Stock",
    slug: "xueqiu-stock-placeholder",
    url: "https://xueqiu.com/",
    type: SourceType.OPINION,
    category: Category.STOCK,
    provider: "xueqiu-placeholder",
    enabled: false,
    fetchIntervalMinutes: 120,
    reliabilityScore: 42,
    notes: "Placeholder only. Do not scrape; verify official access and terms first.",
    config: {},
  },
]

async function main() {
  const db = getDb()
  for (const source of sources) {
    await db.source.upsert({
      where: { slug: source.slug },
      create: source,
      update: source,
    })
  }
  console.log(`Seeded ${sources.length} sources.`)
}

main()
  .catch((error) => {
    console.error(error)
    process.exitCode = 1
  })
  .finally(async () => {
    await getDb().$disconnect()
  })
